### PR TITLE
Require "Secure" for "SameSite=None".

### PR DESCRIPTION
**Pull request by miketaylr**
Opening for discussion, per the last interim group meeting.

This should correspond to https://tools.ietf.org/html/draft-west-cookie-incrementalism-01#section-3.2

### CODE REVIEW

**Comment by miketaylr** [comment]
Can you please review, @chlily1?

**Comment by chlily1** [comment]
> Can you please review, @chlily1?

LGTM, thanks

**Comment by miketaylr** [comment]
cc @mikewest

**Review by mikewest — APPROVED** [review]
LGTM % changelog entry.

**Comment by miketaylr** [comment]
On a gamble, I just rebased this on top of https://github.com/httpwg/http-extensions/pull/1325 (to avoid Changelog merge conflicts). 

So that should land first before merging this.

**Comment by mikewest** [comment]
Hrm. Landing #1325 created conflicts here. I'll resolve those and land this PR this morning.

**Comment by miketaylr** [comment]
> Hrm. Landing #1325 created conflicts here.

My bad. 😿 

(Thanks for fixing!)

**Pull request merged**
