### PR TITLE
[SH] use RWS in inner-list

### PR DESCRIPTION
**Pull request by phluid61**
* update ABNF for inner-list to use RWS
* update parsing algorithm to accept HTAB
* update imports to include RWS and HTAB

For #961

### CODE REVIEW

**Comment by reschke** [comment]
RWS implies "required". Is that really the intent?

**Comment by phluid61** [comment]
Yes. We require spaces between the items in an inner-list, otherwise they can abut.

**Comment by ioggstream** [comment]
*imho* RWS and TABs make things error-prone and difficult to debug.

**Comment by phluid61** [comment]
Just so we're aware, this PR was to address [an issue identified in #961](https://github.com/httpwg/http-extensions/issues/961#issuecomment-549968307) where the ABNF says `OWS` (including htab) but the reference algorithm requires `SP` before `OWS` after an sh-item.

So changing the ABNF to match the algorithm gives:
```
inner-list = "(" OWS [ sh-item *( SP OWS sh-item ) [ SP OWS ] ] ")" *parameter
```

Alternatively, by extending the algorithm to also accept a htab immediately after an item, the ABNF becomes:

```
inner-list = "(" OWS [ sh-item *( RWS sh-item ) OWS ")" *parameter
```

An alternative is to remove the htab altogether, which removes OWS, so we're left with:

```
inner-list = "(" *SP [ sh-item *( 1*SP sh-item ) *SP ")" *parameter
```

Which is fine by me, but removing all OWS is a bigger change.

**Comment by kazuho** [comment]
I think we should retain the use of OWS, rather than removing them or changing (some of) them to RWS.

Not all SH header fields would be generated by a serializer that understands SH. Rather, I'd assume that most of SH header fields would be written by hand, or generated by concatenating strings (in various programming languages).

I do not think we can easily enfoce everyone to insert whitespaces is a particular way (or drop them).

**Comment by mnot** [comment]
@kazuho I'm not as worried about that; tabs in existing headers are _extremely_ uncommon, IME (looking at things like the HTTP Archive dump). If SH implementations are consistent (and they should be if we test well), this will get caught early.

**Comment by kazuho** [comment]
@mnot I'm not worried about tabs. I think it would be fine if the change is going to be either or both of the following and nothing more.
* `OWS` -> `*SP`
* `RWS` -> `1*SP`

**Comment by mnot** [comment]
@kazuho yep +1

**Comment by phluid61** [comment]
I made a new branch (with PR) to see what sort of change is involved replacing `OWS` with `*SP`. It's not as invasive as I'd thought it might be.

**Comment by mnot** [comment]
OBE

**Pull request closed without merging**
