### PR TITLE
Add changes from RFC 6265 section

### LINKED ISSUE #2352: Changes from RFC6265
It'd be nice if there were an appendix summarising the changes. We do this for most updates.

### PR DESCRIPTION
**Pull request by sbingler**
Closes #2352

Summarizes all the major changes from 6265bis, replacing the existing draft-by-draft change log.

### CODE REVIEW

**Comment by sbingler** [comment]
While there are still a couple open issues that may/may not change this PR, I'd still appreciate an initial look.
Thanks!

**Comment by sbingler** [comment]
@mikewest This is ready for review, I don't believe the pending PR needs to be added to this changelog

**Comment by mnot** [comment]
Looks generally reasonable to me. Maybe drop the IANA changes summary (too detailed), and try to lead with the important changes (e.g., drop the errata down to last)?

**Review by mikewest — APPROVED** [review]
Catching up on things after being out sick for a ~week.

This change LGTM. I think the level of detail is appropriate, and I didn't see anything in the line-by-line changelog that jumped out at me as being big enough to consider missing.

**Pull request merged**
