### PR TITLE
Clarify handling of Content-Length and Upload-Complete

### PR DESCRIPTION
**Pull request by Acconut**
Closes https://github.com/httpwg/http-extensions/issues/2544

I am not super sure about the wording here, but this is a start. The sentences seem quite long and maybe the rules could also be expressed in fewer words.

### CODE REVIEW

**Comment by jrflat** [comment]
If the client acknowledged its final upload size at any point (`Upload-Complete: ?1` + `Content-Length`), it should still know it in the future, so I don't think we need a way for the server to echo it in the offset retrieving response. If the server disagrees with the client, then someone's data representation has changed, and we shouldn't continue the upload anyway.

**Comment by guoye-zhang** [comment]
Looks good. Wondering if these could be reduced to SHOULDs though. It wouldn't really affect interop if the server didn't implement this.

**Comment by Acconut** [comment]
> If the client acknowledged its final upload size at any point (`Upload-Complete: ?1` + `Content-Length`), it should still know it in the future, so I don't think we need a way for the server to echo it in the offset retrieving response. If the server disagrees with the client, then someone's data representation has changed, and we shouldn't continue the upload anyway.

Fair point, let's leave such functionality out of the draft.

> Wondering if these could be reduced to SHOULDs though. It wouldn't really affect interop if the server didn't implement this.

While it is true that clients usually won't really notice if the server does or does not support this, I think we can be stricter here and require this additional safety catch here. It will help to create a more standard landscape of resumable upload servers. Unless there is something against requiring this, we can keep it a MUST IMO.

**Comment by Acconut** [comment]
I just updated this PR to use the Upload-Complete header as agreed on in #2500

**Comment by guoye-zhang** [comment]
The arguments for SHOULD are:

1. This check requires additional code and complexity. MUSTs are situations that a minimal implementation has to handle anyway and we are just strict about how to handle them.
2. For people using chunked uploads, this check is only useful if the last chunk is interrupted which is sort of an edge case. Maybe we can generalize the check if we adopt ranged PATCH.

I don't have a strong opinion on this, so either way is OK with me.

**Review by guoye-zhang — APPROVED** [review]

**Pull request merged**
