### PR TITLE
Make Capsule Protocol support mandatory for servers

### PR DESCRIPTION
**Pull request by bemasc**
This increases the complexity of a minimal server implementation and decreases the complexity of a rich client implementation.

Addresses #2855

### CODE REVIEW

**Review by tfpauly — APPROVED** [review]

**Review by DavidSchinazi — APPROVED** [review]
Thanks!

**Comment by DavidSchinazi** [comment]
Another option would be to say that connect-tcp always uses capsules, that would reduce complexity even further

**Comment by bemasc** [comment]
> Another option would be to say that connect-tcp always uses capsules, that would reduce complexity even further

That would reduce the complexity of a rich server implementation, but it would increase the complexity of a minimal client implementation.  I don't think that is a wise trade.

**Comment by DavidSchinazi** [comment]
Do we think minimal client implementations will exist? I was imagining that they'd use regular CONNECT

**Comment by LPardue** [comment]
The spec probably wants more language to describe what a client should do when a server does not enable the capsule protocol, since thst a failure mode for this optional behaviour.

**Comment by bemasc** [comment]
@DavidSchinazi Template-based configuration is valuable with or without the capsule protocol.  Also, if you're not actually using capsules, it adds bandwidth overhead without any benefit.

@LPardue We don't usually say "the server MUST $X, but if it doesn't the client SHOULD $Y".  Is there a reason why that is necessary in this case?

**Comment by LPardue** [comment]
It seems weird to me that a server that the server echos something back that the client doesn't check.  

Since the server has a MUST requirement to process whatever format the client tells it, we could just drop the response header and state that a 2xx is the signal that server accepted connect-tcp with or without capsules.

**Comment by bemasc** [comment]
The response header is for the benefit of intermediaries.  Clients don't rely on it.  This is also true for CONNECT-UDP.

**Comment by LPardue** [comment]
That's a good point and might be worth saying explicitly in the text.

However, we do have a pattern in RFC9298 that levies requirements on request and response message and says "if any of these requirements are not met, the client MUST treat the procying attempt as failed and abort the request". Since connect-tcp levies a MUST about capsule-protocol on the response message, using similar text seems consistent to me.

**Pull request merged**
