### PR TITLE
"identity" is not a valid field value for "Content-Encoding"

### PR DESCRIPTION
**Pull request by reschke**
(it only exists in Accept-Encoding)

### CODE REVIEW

**Comment by ioggstream** [comment]
Hi Julian, thanks for your review! 

Reading https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.content-encoding I understand that the `content-coding` allowed values are defined her https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.6.1.2.p.5

Reading the `Accept-Encoding` it seems that `identity` shouldn't be on that list, but iiuc it's there.
Ideas?

**Comment by LPardue** [comment]
not that it is a canonical source of reference but the MDN article is also a bit weird wrt identity https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

**Comment by reschke** [comment]
It's in the registry because it has a special meaning in Accept-Encoding, and thus can not ever be defined as actual encoding.

And yes, the comment in the registry table could be clearer.

**Comment by ioggstream** [comment]
@reschke can we "fix" the Semantics document before changing Digest?

**Comment by reschke** [comment]
I don't see why one is a precondition for the other...

**Comment by ioggstream** [comment]
If we are sure that there's an issue in semantics, it's ok. LGTM

**Pull request merged**
