### PR TITLE
Add changelog since -03

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

Adds changelog since -03

### CODE REVIEW

**Comment by LPardue** [comment]
I think we missed the parameter changes?

Also I just realised that the draft order is ascending, folks typically do it in descending order so the most recent changes are easier to see

**Comment by ioggstream** [comment]
1. The parameter didn't land yet :( do you have a solution for Mark's point? https://github.com/httpwg/http-extensions/pull/1259#discussion_r501403171
2. ok :)

**Review by pes2020kk — COMMENTED** [review]
ios 14

**Comment by ioggstream** [comment]
@LPardue seems spam: should we report it to gh?

**Pull request merged**
