### PR TITLE
Revert "(Content-)Location in QUERY"

### PR DESCRIPTION
**Pull request by reschke**
Reverts httpwg/http-extensions#2851

### CODE REVIEW

**Comment by reschke** [comment]
(sorry for accidentally merging, now reverted)

**Comment by reschke** [comment]
Q; in the Security Considerations, should we mention that using L or C-L needs to be done carefully when the original QUERY method's behavior was subject to some kind of access control?

**Comment by MikeBishop** [comment]
I'm confused. #2851 appears to be in `main`, while this PR proposes reverting it. Was the reverse intended?

**Comment by reschke** [comment]
I probably screwed up things when I accidentally pressed "merge" when I wanted "rebase".

Let me try to fix it today.

**Comment by reschke** [comment]
Ok, I have restored the original branch, but I'm not sure how to remove the commits from main.

I think something like (on main)
---
git reset d26f7c3b9f38badc3598e742824e82667df2f092
---

ought to work, but I'm not totally convinced.

Maybe @mnot can help?

**Comment by MikeBishop** [comment]
Three options I can see:

- If there's nothing else merged we need to keep, `git reset [last good commit] && git push -f` will work, but it's potentially disruptive if anything has been merged from other documents or people have cloned/pulled in the meantime.
- Merge the reversion PR to main; it's a lot of unneeded commits, but it doesn't lose anything and it's consistent.
- `git show [last good commit]:draft-ietf-httpbis-safe-method-w-body.xml > draft-ietf-httpbis-safe-method-w-body.xml && git add draft-ietf-httpbis-safe-method-w-body.xml && git commit -m "Revert PR#2851"` would also do it as a single commit to revert the draft without touching anything else.

**Comment by reschke** [comment]
In the meantime, I did the simplest thing:

- recreated the branch without reverts
- copied the previous start of the draft over to main, so we don't have the contents of the PR in there. That left the version history uglx, but there we go...

**Pull request closed without merging**
