### PR TITLE
Remove requirement to clear Client Hint preferences on browser history clear

### PR DESCRIPTION
**Pull request by amtunlimited**
Fix: #1238 

@yoavweiss 
@igrigorik 
@davidben

### CODE REVIEW

**Comment by amtunlimited** [comment]
Adjusted scope of change because the Client Hints proposal is further along in the process than I realized

**Comment by yoavweiss** [comment]
This LGTM based on the discussion in #1238

@mnot - thoughts on landing this at this point? Note that https://github.com/httpwg/http-extensions/pull/1282 means we'd probably need to republish a draft anyway.

**Comment by mnot** [comment]
I think you can do both of these changes in AUTH48, but you should send an e-mail to the list giving folks a heads-up first. Note that because the draft is now at the RFC Editor, publishing a new revision probably isn't going to help.

**Comment by reschke** [comment]
Am 06.10.2020 um 05:15 schrieb Mark Nottingham:
> I think you can do both of these changes in AUTH48, but you should send
> an e-mail to the list giving folks a heads-up first. Note that because
> the draft is now at the RFC Editor, publishing a new revision probably
> isn't going to help.
> ...

FWIW, and IMHO, publishing a new version is more transparent, and *will*
work if the RPC hasn't started editing yet, and if the AD is ok with it.

Best regards, Julian

**Comment by amtunlimited** [comment]
I'm going to go ahead and close this.

**Pull request closed without merging**
