### PR TITLE
Added a small blurb referencing client range-end considerations from section 5

### PR DESCRIPTION
**Pull request by craigpratt**
Also considering if "Security Considerations" can be "Compatibility Considerations".

### CODE REVIEW

**Comment by craigpratt** [comment]
I haven't renamed "Security Considerations" in this version. And I have no issue with calling this "Compatibility Considerations". But I have some recollection that this is a required section...

**Comment by martinthomson** [comment]
Yeah don't do that or various people will start to scream at you :)

**Comment by craigpratt** [comment]
Call me a perfectionist, but on reread, I realized there was a cleaner/shorter way to clarify. 

Let me know if you have any objection...

**Comment by craigpratt** [comment]
Thanks Martin!

**Pull request merged**
