### PR TITLE
RFC6265bis: Include 'host-only-flag' when calculating uniqueness.

### PR DESCRIPTION
**Pull request by mikewest**
Closes https://github.com/httpwg/http-extensions/issues/199

@johnwilander, mind taking a look?

### CODE REVIEW

**Comment by mikewest** [comment]
(@mnot, would you mind adding @johnwilander to the repo as a collaborator so I can ask him to review via the GitHub tool? :) )

**Comment by mikewest** [comment]
Ping.

**Comment by mnot** [comment]
Invite was sent a while back. Still listed as "pending."

**Comment by mikewest** [comment]
> I probably need to read more of the context but would it be useful to point out that this is an internal flag for the user agent? It is, right? Inferred from whether the setting of the cookie included the domain or not.

It is an internal flag, but I don't think the PR needs additional documentation. The change we're making is in the middle of an algorithm, and `host-only-flag` is basically a variable that was set earlier in the process. I think folks reading the document will understand that. :)

**Comment by mikewest** [comment]
Thanks for the review! I'll merge this, and look forward to your PR adding yourself as an editor.

**Pull request merged**
