### PR TITLE
Acknowledge David S

### PR DESCRIPTION
**Pull request by martinthomson**
@chris-wood WDYT?

### CODE REVIEW

**Review by chris-wood — APPROVED** [review]

**Review by DavidSchinazi — APPROVED** [review]
👋

**Comment by DavidSchinazi** [comment]
@martinthomson out of curiosity what does this `{{{Person Name}}}` syntax do? The finished product looks the same and I couldn't find documentation for it in kramdown-rfc

**Comment by martinthomson** [comment]
That produces `<xref fullname="Person Name"/>`, which ensures that there is a smaller diff when the RPC gets their hands on the document later.  What is really cool is that you can do `{{{ǝɯɐN uosɹǝԀ}}}{: asciiFullname="Person Name"}` and a real name can be shown (with an ASCII translation).  Or, if you leave off the attribute, you can just put arbitrary unicode in the draft...

**Comment by DavidSchinazi** [comment]
Thanks!

**Pull request merged**
