### PR TITLE
client-cert: Mention that origin server access control decisions can be conveyed with a 403 or by selecting response content

### PR DESCRIPTION
**Pull request by bc-pi**
client-cert: Mention that origin server access control decisions can be conveyed with a 403 or by selecting response content

#1935

### CODE REVIEW

**Comment by davidben** [comment]
Do you envision that clients would drop their client cert cache in response to this 403? (They currently do not.) If so, how would that interact with subresources on the page?

**Comment by bc-pi** [comment]
I honestly don't envision any change in client behavior. I realize that doesn't address your concern. But I believe doing anything more is firmly beyond the scope of this draft. The sentence added by this PR is only aiming to fulfill Tommy's suggestion at the last virtual interim and in the issue https://github.com/httpwg/http-extensions/issues/1935#issuecomment-1142682468

**Comment by martinthomson** [comment]
You might want to explain that David's concern is a genuine problem that this doesn't solve, something like:

> Note that TLS clients that rely on error indications at the TLS layer for an unacceptable certificate will not receive those signals.

**Review by tfpauly — APPROVED** [review]

**Comment by bc-pi** [comment]
Thanks Martin. I'll add that note.

**Review by MikeBishop — APPROVED** [review]
This is sufficient.  A similar experience exists today when a client presents a certificate which is valid, but which does not grant access to the requested resource.  While it's not ideal in certain ways -- the client might possess other certificates that would grant access if given an appropriate selector -- the server might also prefer not to share that list.

This draft isn't attempting to create new solutions from scratch -- it's attempting to outline what is currently done in assorted custom ways to help coalesce these into a single format.  Those custom mechanisms don't provide TLS alert translation either, so far as I'm aware.

**Pull request merged**
