### PR TITLE
[WIP] EU Cookie Law Mechanisms

### PR DESCRIPTION
**Pull request by ttacker**
* Add attributes to Set-Cookie syntax
* Update Set-Cookie semantics
* Add subcomponent algorithms and todo throughout

I had started work on this PR to address issue #945 before it was closed. I thought other people might like to see my initial thoughts, so I created this PR as a WIP. I'm not requesting it be merged, and it can be closed; but if anyone wants to provide feedback, that would be welcome. Thanks!

### CODE REVIEW

**Comment by petkivim** [comment]
It might me a good idea to include the action in the Consent attribute's value or alternatively, define separate attributes for the action and time, e.g.:
```
consent-av        = "Consent=" consent-action; consent-date
consent-action    = "Unconfirmed" / "Granted" / "Revoked"
consent-date      = <IMF-fixdate>
                      ; IMF-fixdate defined in [RFC7231], Section 7.1.1.1
```

OR

```
consent-action-av  = "ConsentAction=" consent-action
consent-action     = "Unconfirmed" / "Granted" / "Revoked"
consent-date-av    = "ConsentDate=" consent-date
consent-date       = <IMF-fixdate>
                      ; IMF-fixdate defined in [RFC7231], Section 7.1.1.1
```

In this way it is possible to prove that consent occurred, even if subsequently withdrawn. In case the Consent attribute is just unset when consent is withdrawn, there's no trace that consent occurred earlier.

**Comment by ioggstream** [comment]
As suggested by @mnot I propose to create a new draft for addressing that, which could be easily integrated or extend current one.

I'm volunteering as co-editor and I can setup the repo with an automatic draft build in minutes. @ttacker

**Comment by awwright** [comment]
Doesn't consent occur when the user-agent saves the cookie to storage? Saving cookies is something the user-agent must opt into on behalf of the user; not by the server.

The one thing that seems to be missing is a way to link to the cookie policy; but didn't P3P already standardize a way to do this?

**Comment by pbowyer** [comment]
> Doesn't consent occur when the user-agent saves the cookie to storage? Saving cookies is something the user-agent must opt into on behalf of the user; not by the server.

Yes that is correct.

**Comment by ioggstream** [comment]
> didn't P3P already standardize a way to do this?

afaik P3P is somewhat deprecated, see https://bugzilla.mozilla.org/show_bug.cgi?id=225287#c12

**Comment by chlily1** [comment]
> I'm not requesting it be merged, and it can be closed

Thanks, I will go ahead and close this.

**Pull request closed without merging**
