### PR TITLE
digest: subsections of unnumbered sections are already unnumbered [xml2rfc issue]

### PR DESCRIPTION
**Pull request by reschke**

### CODE REVIEW

**Comment by ioggstream** [comment]
Thanks for the PR! The CI gives this error: 
> /github/workspace/draft-ietf-httpbis-digest-headers.xml(1743): Error: Did not expect a numbered section under an unnumbered parent section (seen on line 1740)

**Comment by reschke** [comment]
Oh.

That's a bug in xml2rfc then (I didn't realize that because I use rfc2629.xslt). So ignore this PR for now until the bug is fixed.

**Comment by reschke** [comment]
See <https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/556>.

**Comment by mnot** [comment]
Can this PR (and branch) be deleted?

**Pull request closed without merging**
