### PR TITLE
Restore cookie-name = token

### PR DESCRIPTION
**Pull request by markt-asf**
This is a partial revert of 5469d51 from PR #1145

### CODE REVIEW

**Comment by mikewest** [comment]
Talked with @sbingler a moment ago. I think there are some additional changes that will be necessary, but I don't object to the idea of this revert. Seems like a mistake in the original PR.

**Comment by markt-asf** [comment]
Happy to amend the PR if you can give me an idea of what additional changes are required.

**Comment by sbingler** [comment]
I wrote up a change that should cover all the points we want to make.

Namely, we still want UAs to accept that larger character set while encouraging server to use the more limited character set.

**Review by mikewest — APPROVED** [review]
This looks reasonable to me, thanks to you both.

**Pull request merged**
