### PR TITLE
Security for spoofed certs

### PR DESCRIPTION
**Pull request by MikeBishop**
Text giving recommendations for guarding against spoofed certs.

### CODE REVIEW

**Comment by martinthomson** [comment]
The text on pinning is fine.  If the intent is expand on the authentication requirements for alternatives, the first sentence would suffice.

I'm concerned that the "additional requirements" you describe here might lead to interoperability problems.  If these aren't specified, we are left to guess what the validation requirements are for any given client.  I recognize that failure to authenticate an alternative doesn't necessarily translate into a fatal error - the alternative is just not used.  However, I'm wondering what the motivation for the change is.

**Comment by MikeBishop** [comment]
This is from #76, which I should have tagged.  You argued against the spec requiring an identical cert, and I agree that synchronization and security of the cert could certainly be an issue.  However, the client might already have some data about the certs used by the origin and could reasonably expect some similarity between them.

As I said in the issue, I think cautious implementations will probably do *something* here, and I'd prefer the possibility to be mentioned in the spec so it's something operators will be aware of.

**Comment by reschke** [comment]
@martinthomson are you ok with this proposal?

**Comment by martinthomson** [comment]
Yes, it is what we discussed in the meeting.

**Pull request merged**
