### PR TITLE
Add QUERY example to introduction

### LINKED ISSUE #2171: Example in introduction
The Introduction has examples of how to do things without QUERY, but no examples of QUERY itself. Having one would help readers understand the method more easily.

### PR DESCRIPTION
**Pull request by mnot**
Fixes #2171

### CODE REVIEW

**Review by reschke — CHANGES_REQUESTED** [review]
Yes, but.

If we do this, we'll also need to define the QUERY semantics for this content type, no?

**Comment by reschke** [comment]
> Yes, but.
> 
> If we do this, we'll also need to define the QUERY semantics for this content type, no?

Should I gave that a try?

**Comment by mnot** [comment]
That'd be good -- I'm curious to see how that works :)

**Comment by sandstrom** [comment]
Out of curiosity, what's the status for this (not this issue, but QUERY in general)?

I think QUERY is a great addition to the HTTP spec, and would love to start using it.

**Review by reschke — APPROVED** [review]

**Comment by reschke** [comment]
fixed via a2332a521ddb42e0c7d0c3b6f9a636b2684fcecf

**Pull request closed without merging**
