### PR TITLE
Expect-CT: update text about http-equiv

### PR DESCRIPTION
**Pull request by estark37**

### CODE REVIEW

**Comment by estark37** [comment]
@reschke @mnot thanks for the explanation/suggestion on the list. Does this look about right to you?

**Comment by mnot** [comment]
LGTM.

**Comment by reschke** [comment]
- avoid lowercase "should" unless you refer to [RFC8174] in "Terminology"

FWIW, I still think that citing both HTML specs does not help the reader, and that the whole section isn't needed. If it was needed, why don't we say the same thing in draft-ietf-httpbis-replay-03?

**Comment by estark37** [comment]
I don't have any strong feelings on this, I'm happy to just remove it. I cribbed it from HPKP originally. (https://tools.ietf.org/html/rfc7469#section-2.3.4)

**Comment by estark37** [comment]
This is removed now.

**Comment by reschke** [comment]
LGTM, and thanks for pointing to RFC 7469. @mnot - should we raise an erratum for that spec?

**Comment by reschke** [comment]
FWIW: https://www.rfc-editor.org/errata/eid5377

**Pull request merged**
