### PR TITLE
sh: Remove non-ASCII chars

### PR DESCRIPTION
**Pull request by clelland**

### CODE REVIEW

**Comment by clelland** [comment]
This just fixes a couple of non-ASCII U+2212 MINUS-SIGN characters that crept in with #1104.

**Comment by reschke** [comment]
Actually, they've been there before. What #1104 broke was the encoding.

**Comment by clelland** [comment]
Ahh -- I thought that was GitHub just exposing the UTF8-ness in the diff when I looked at it.

I'll leave it to editors to decide whether non-ASCII is appropriate in the markdown version of the spec; I'm sure that the IETF has a process for dealing with it when it needs to be a text RFC.

**Comment by reschke** [comment]
No, this really should be an ASCII minus.

**Comment by LPardue** [comment]
https://mailarchive.ietf.org/arch/msg/rfc-interest/hWOHbgqeEj0vRRoj-qsFcI10_jQ/

**Pull request merged**
